= giblish
:docid: G-001
:numbered:
:toc: preamble
:toclevels: 1

image::https://github.com/rillbert/giblish/actions/workflows/unit_tests.yml/badge.svg["Build Status"]


giblish converts a source directory tree containing AsciiDoc files to a destination directory tree containing the corresponding html or pdf files. It adds some handy tools for easier navigation of the resulting destination tree.

.Two-liner conversion
[source, bash]
----
# install giblish (requires a working ruby installation on the system)
gem install giblish
# convert all adoc files recursively under 'my/src' and place them (recursively) under "the/dest"
$ giblish my/src the/dest
----

== Examples

IMPORTANT: The examples below are *not* the official documentation for the corresponding projects.

[cols="1,1,5"]
|===
|Project |Link to example |Comment

|The `giblish` documentation
|https://www.rillbert.se/giblish_examples/giblish/main/index.html[here]
|The documentation of giblish (same as you find in GitHub).

|Raspberry Pi documentation
|https://www.rillbert.se/giblish_examples/rpi_docs/giblish_example/index.html[example]
|The project's official documentation site uses Jekyl for site generation, the link points to a mirror where some small tweaks to the docs were made to make them suitable for generation with giblish.

|The *old* asciidoctor docs
|https://www.rillbert.se/giblish_examples/asciidoctor_docs/master/newindex.html[example]
|An example of how giblish can generate the master branch of the *old, deprecated* official asciidoc.org documentation git repo.

|===

== `giblish` features

The features of giblish include:

 * Simple conversion of whole document trees into both html and pdf.
 * Customizable index pages that list all rendered documents with clickable links.
 * Generate separate destination trees per branch in a git repo in one go (see examples below).
 * Document ids - a (non-standard) way of referencing other documents in the same tree, you can use document ids to:
 ** Reference one doc in the source tree from another doc without depending on file names or relative paths. The referenced doc can thus be moved within the source tree or change its file name and the reference will still be valid.
 ** Validate doc id references during document rendering and thus be alerted to any invalid doc id references.
 ** Let giblish generate a clickable graph of all document references (requires graphviz and the 'dot' tool).
 * Text-search - a stripped-down, but nonetheless useful, text-search of your html documents. This requires that you publish your docs to a web-server and setup an application on that same web-server. `giblish` provides most of the scaffolding though.

== Dependencies and credits

Giblish uses the awesome `asciidoctor` and `asciidoctor-pdf` projects under the hood. Thank you @mojavelinux and others for making these brilliant tools available!!

The official documentation of these tools as well as extensive information about the AsciiDoc syntax can be found at https://docs.asciidoctor.org

== Installation

 gem install giblish

Want to get started straight away? Go directly to the <<usage_examples>>.

=== Some caveats

When using giblish for generating docs the following applies:

 * giblish *will overwrite* files with the same name in the destination directory.
 * giblish requires that the git working tree and index of the repo containing source documents are clean when generating documentation.
 * giblish will make explicit check-outs of all the branches or tags that matches the selection criteria. The working dir of the source git repo will thus have the last branch that giblish checked-out as the current branch after doc generation.

== Document ids and the reference graph

NOTE: This is a non-standard extension of asciidoc. If you use this feature, you will need to generate your documents using giblish to make this work as intended.

giblish extends the cross reference concept in asciidoc with a _document id_ mechanism. To use this, you need to:

 . Add a `:docid:` entry in your document's header section. The doc id can consist of up to 10 characters and must be unique within the set of documents generated by giblish.
 . Refer to a document using the syntax `pass:[<<:docid:a_doc_id>>]` where `a_doc_id` is the doc id of a document in the same git repo.
 . Run giblish with the -d switch when generating documents.

Using doc ids makes it possible for giblish to do two things:

 . Make references from one document in the tree to another work even if one of the documents have been moved within the document source tree.
 . Produce a clickable 'map' of the generated documents where the different references are clearly seen. This feature require that the 'dot' tool, part of the graphwiz package is installed on the machine where giblish is run.

The use of the -d switch makes giblish parse the document twice, once to map up the doc ids and all references to them, once to actually generate the output documentation. Thus, you pay a performance penalty but this should not be a big inconvenience since the generation is quite fast in itself.

=== Example of using the docid feature

Consider that you have two documents located somewhere in the same folder tree, document one and document two. You could then use the docid feature of giblish to refer to one document from the other as in the example below.

Example document one::

[source,asciidoc]
----
= Document one
:toc:
:numbered:
:docid: AB-001

== Purpose

To illustrate the use of doc id.
----

Example document two::
[source,asciidoc]
----
= Document two
:toc:
:numbered:
:docid: AB-002

== Purpose

To illustrate the use of doc id. You can refer to document one as <<:docid:AB-001>>. This will display a clickable link with the doc id (AB-001 in this case).

You can use the same syntax as the normal asciidoc cross-ref but replace 'xref' with ':docid:' as shown below:

 * <<:docid:AB-002#purpose>> to refer to a specific section or anchor.
 * <<:docid:AB-002#purpose,The purpose section>> to refer to a specific section and display a specific text for the link.
----

The above reference will work even if either document changes location or file name as long as both documents are parsed by giblish in the same run.

[[usage_examples]]
== Usage Examples

A number of use cases for giblish in increasing order of complexity.

=== Get available options

 giblish -h

=== Giblish html 'hello world'

 giblish my_src_root my_dst_root

 * convert all .adoc or .ADOC files under the dir `my_src_root` to html and place the resulting files under the `my_dst_root` dir.
 * generate an index page named `index.html` that contains links and some info about the converted files. The file is placed in the `my_dst_root` dir.

The default asciidoctor css will be used in the html conversion.

=== Giblish pdf 'hello world'

 giblish -f pdf my_src_root my_dst_root

 * convert all .adoc or .ADOC files under the dir `my_src_root` to pdf and place the resulting files under the `my_dst_root` dir.
 * generate an index page named `index.pdf` that contains links and some info about the converted files. The file is placed in the `my_dst_root` dir.

The default asciidoctor pdf theme will be used in the pdf conversion.

=== Customize the index pages generated by giblish

Add a file `idx_template.erb` under a directory of your choice, in this example `style_resources` is used. An example of the available customization options is https://github.com/rillbert/giblish/blob/personal/rillbert/data/resources/erb/idx_template.erb[this file] from the giblish test data set.

Invoke `giblish` with the resource directory set using the `-r` flag.

 giblish -r style_resource my_src_root my_dst_root

Your erb template is used to generate the index page(es).

=== Using a custom css for the generated html

Generate html that can be browsed locally from file:://<my_dst_root>.

 giblish -r path/to/my/resources -s mylayout my_src_root my_dst_root

 * convert all .adoc or .ADOC files under the dir `my_src_root` to html and place the resulting files under the `my_dst_root` dir.
 * generate an index page named `index.html` that contains links and some info about the converted files. The file is placed in the `my_dst_root` dir.
 * copy everything found under `<working_dir>/path/to/my/resources` to `my_dst_root/web_assets`
 * link all generated html files to the mylayout.css found somewhere under `/web_assets`

=== Using a custom pdf theme for the generated pdfs

 giblish -f pdf -r path/to/my/resources -s mylayout my_src_root my_dst_root

 * convert all .adoc or .ADOC files under the dir `my_src_root` to pdf and place the resulting files under the `my_dst_root` dir. some info about the converted files. The file is placed in the `my_dst_root` dir.
 * the pdfs will be rendered using the theme file named mylayout.yml found somewhere under `<working_dir>/path/to/my/resources`

=== Generate html from multiple git branches

 giblish -g "feature" my_src_root my_dst_root

 * check-out each branch matching the regexp "feature" in turn
 * for each checked-out branch,
 ** convert the .adoc or .ADOC files under the dir `my_src_root` to html.
 ** place the resulting files under the `my_dst_root/<branch_name>` dir.
 ** generate an index page named `index.html` that contains links and some info about the converted files. The file is placed in the `my_dst_root/<branch_name` dir.
 * generate a summary page containing links to a all branches and place it in the `my_dst_root` dir.

== Contributing

If you want to contribute to giblish, great :) Use the standard GitHub flow of forking the repo and submit a pull request.

Pull requests must meet the following to be considered for merging:

 * Tests have been added for new or updated functionality
 * The code has been linted using the `standardrb` tool.
 ** The version of standardrb shall be the same as the one used in the target branch for the PR.

To develop on giblish, you:

 . Install ruby on your local machine (rbenv is a good choice for handling ruby installations)
 . Install necessary dependencies to install the ruby 'mathematica' gem, see eg https://github.com/gjtorikian/mathematical/blob/47041d5492cc7c5f04105031430fb44119406f49/script/install_linux_deps
 . Install graphviz
 . Clone or fork the repository
 . Run the `bin/setup` script from a bash prompt

// === Publish the asciidoctor.org documents with text search

// giblish can be used to generate html docs suitable for serving via a web server (e.g. Apache). You can use the cgi script included in the giblish gem to provide text search capabilities.

// Here is an example of how to publish the docs in the official asciidoctor.org git repo to a web server, including index pages and text search.

// NOTE: No consideration has been taken to how permissions are set up on the web server. Just running the below commands as-is on e.g.a standard apache set-up will bail out with 'permission denied' errors.

// ==== Generating the html documents

// The example assumes that you have one machine where you generate the documents and another machine that runs a web server to which you have ssh access.

// The generated docs shall be accessible via _www.example.com/adocorg/with_search_

// You need to provide two pieces of deployment info to giblish when generating the documents:

//  * the uri path where to access the deployed docs (/adocorg/with_search in this example)
//  * the path in the local file system on the web server where the search data can be accessed
//    (/var/www/html/site_1/adocorg/with_search in this example)

// The following commands will generate the asciidoctor.org documentation and deploy the result to the web server.

//  . Clone the asciidoctor doc repo to your development machine
// +
//  git clone https://github.com/asciidoctor/asciidoctor.org.git

//  . Generate the html documentation with the correct deployment info
// +
//  giblish -j '^.*_include.*' -m -mp /var/www/html/site_1/adocorg/with_search -w /adocorg/with_search -g master --index-basename "myindex" asciidoctor.org/docs ./generated_docs
// +
// Explanation of the parameters and arguments::
//  * *pass:[-j '^.*_include.*']* - exclude everything in the __include_ directory. (the
//                                  asciidoctor.org repo stores partial docs here).
//  * *-m* - assemble the necessary search data to support text search and include this data as part of
//           the generated documents.
//  * *-mp /var/www/html/site_1/adocorg/with_search* - the file system path on the deployment machine where
//                                                     the search data is located
//  * *-w /adocorg/with_search* - the uri path to the deployed docs
//  * *-g master* - publish all git branches that matches the regexp 'master' (i.e. only the 'master'
//                  branch).
//  * *--index-basename "myindex"* - change the default name (index) that giblish uses for the generated
//                                   index page. This is needed since asciidoctor.org contains an
//                                   "index.adoc" file that would otherwise be overwritten by giblish.
//  * *asciidoctor.org/docs* - the root of the source document tree.
//  * *./generated_docs* - a temporary storage for the generated html docs on the local system.
// +

//  . Copy the generated files to the web server

//  scp -r ./generated_docs rillbert@my.web.server.org:/var/www/adocorg/with_search/.
// +


// ==== Copy the text search script to the web server

// This only needs to be done once (or if a new version of giblish breaks the currently used API).

// IMPORTANT: The current version of giblish expects the script to be found at the URI path `/cgi-bin/giblish-search.cgi`. This might be customizable in future versions but is currently hard-coded. Thus, if your web-server serves pages at www.mywebsite.com, the search script must be accessible at www.mywebsite.com/cgi-bin/giblish-search.cgi

//  . Find the server side script that implements text search that is included with giblish

//  gem which giblish
// +

// In my case this returns `/var/lib/ruby/gems/2.4.0/gems/giblish-0.5.2/lib/giblish.rb`. This means that I will find the script in the same directory, i.e. `/var/lib/ruby/gems/2.4.0/gems/giblish-0.5.2/lib`.

//  . Copy the server side script to the /cgi-bin dir on the web server. In this example the cgi-bin dir is configured to be `/var/www/cgi-bin`
// +
//  scp /var/lib/ruby/gems/2.4.0/gems/giblish-0.5.2/lib/giblish-search.cgi rillbert@my.web.server.org:/var/www/cgi-bin/giblish-search.cgi
