# frozen_string_literal: true

require "pathname"
require "git"

require_relative "../pathtree"
require_relative "../gititf"
require_relative "verbatimtree"

module Giblish
  class IndexSrcFromTree
    attr_reader :adoc_source

    # The fixed heading of the table used to display file history
    HISTORY_TABLE_HEADING = <<~HISTORY_HEADER
      File history::
  
      [cols=\"2,3,8\",options=\"header\"]
      |===
      |Date |Author |Message
    HISTORY_HEADER

    # options:
    def initialize(src_tree)
      @adoc_source = <<~DOC_STR
        #{title}
        #{subtitle(src_tree)}
        #{header}

        #{generation_info}

        #{tree(src_tree)}

        #{document_details(src_tree)}

        #{footer}
      DOC_STR
    end

    protected

    def title
      "= Document index"
    end

    def subtitle(src_tree)
      "from #{src_tree.pathname}"
    end

    def header
      ":icons: font"
    end

    def generation_info
      "*Generated by Giblish at:* #{Time.now.strftime("%Y-%m-%d %H:%M")}"
    end

    def tree(src_tree)
      VerbatimTree.new(src_tree).source
    end

    def add_depgraph_id
      # include link to dependency graph if it exists
      <<~DEPGRAPH_STR
        _A visual graph of document dependencies can be found
        <<./graph.adoc#,here>>
      DEPGRAPH_STR
    end

    def document_details(src_tree)
      details_str = +"== Document details\n\n"

      src_tree.traverse_preorder do |_level, node|
        next unless node.leaf?

        d = node.data
        details_str << (d.converted ? document_detail(d) : document_detail_fail(d))
      end
      details_str
    end

    def footer
      ""
    end

    # return the adoc string for displaying the source file
    def display_source_file(doc_info)
      <<~SRC_FILE_TXT
        Source file::
        #{doc_info.src_file}
      SRC_FILE_TXT
    end

    private

    # return info about any conversion issues during the
    # asciidoctor conversion
    def conversion_issues(doc_info)
      return "" if doc_info.stderr.empty?

      # extract conversion warnings from asciddoctor std err
      conv_warnings = doc_info.stderr.gsub(/^/, " * ")

      # assemble info to index page
      <<~CONV_INFO
        Conversion issues::

        #{conv_warnings}
      CONV_INFO
    end

    def history_info(doc_info)
      return "" unless doc_info.history

      str = +HISTORY_TABLE_HEADING

      # Generate table rows of history information
      doc_info.history.each do |h|
        str << <<~HISTORY_ROW
          |#{h.date.strftime("%Y-%m-%d")}
          |#{h.author}
          |#{h.message}
  
        HISTORY_ROW
      end
      str << "|===\n\n"
    end

    def document_detail_fail(doc_info)
      <<~FAIL_INFO
        === #{doc_info.src_file}

        #{display_source_file(doc_info)}

        Error detail::
        #{doc_info.stderr}

        ''''

      FAIL_INFO
    end

    # Show some details about file content
    def document_detail(doc_info)
      <<~DETAIL_SRC
        [[#{Giblish.to_valid_id(doc_info.title.encode("utf-8"))}]]
        === #{doc_info.title.encode("utf-8")}

        #{"Doc id::\n_#{doc_info.doc_id}_" unless doc_info.doc_id.nil?}

        #{"Purpose::\n#{doc_info.purpose_str}" unless doc_info.purpose_str.to_s.empty?}

        #{conversion_issues doc_info}

        #{display_source_file(doc_info)}

        #{history_info doc_info}

        ''''

      DETAIL_SRC
    end
  end

  class IndexTreeBuilder
    attr_reader :src_tree

    def initialize(dst_top_path)
      reset(dst_top_path)
    end

    def reset(dst_top_path)
      @dst_top_path = dst_top_path
      @src_root = PathTree.new(dst_top_path)
      @src_tree = @src_root.node(@dst_top_path, from_root: true)
      self
    end

    def run(input_node)
      # only care about dirs under dst_top_path
      return if input_node.leaf? || (input_node.pathname <=> @dst_top_path) == -1

      # Preconditions:
      # - All real adoc files have already been converted
      # - The resulting dst_tree is accessible
      #
      # 1. Build a virtual source tree where each node is a dir
      # index
      # 2. Convert the virtual source tree to the same dst as the
      # adoc files.

      index_dir = input_node.pathname.relative_path_from(@dst_top_path).cleanpath
      Giblog.logger.info { "Setting up index for #{index_dir}" }
      source = IndexSrcFromTree.new(input_node)
      @src_tree.add_descendants(index_dir / "index.adoc", source)
    end
  end
end
