name: Giblish CI checks

on:
  push:
    branches: [ personal/rillbert/*, main ]

jobs:
  test-gran:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ "3.3", "3.4" ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Ruby and install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        working-directory: gran
    - name: Run gran tests
      working-directory: gran
      run: bundle exec rake test
    - name: Run gran linter
      working-directory: gran
      run: bundle exec rake standard

  test-giblish:
    runs-on: ubuntu-latest
    needs: test-gran
    strategy:
      matrix:
        ruby-version: [ "3.3", "3.4" ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          binutils \
          graphviz \
          libpango1.0-dev \
          libgdk-pixbuf2.0-dev \
          libxml2-dev \
          libcairo2-dev \
          libwebp-dev \
          libzstd-dev \
          cmake
    - name: Set up Ruby and install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        working-directory: giblish
    - name: Run giblish tests
      working-directory: giblish
      run: bundle exec rake test
    - name: Run giblish linter
      working-directory: giblish
      run: bundle exec rake standard
