#!/bin/bash
#

# set this to the repo root where the working tree exists
WORKING_TREE_ROOT="/the/path/to/the/stage/repo"
# set this to the publish root dir served by a web server
DST_DIR="/var/www/rillbert_se/docs"
# set this to the top dir to look for docs under in the
# staging repo.
SRC_DIR="."

# Make config available in subshell
export WORKING_TREE_ROOT
export DST_DIR
export SRC_DIR

# read the input from git...not currently used.
# it could for example be used to filter on git branches
#
# while read line
# do
#   echo "git ref: $line"
# done < /dev/stdin

echo "Post update hook running..."
(
  cd "${WORKING_TREE_ROOT}"

  # need to unset the GIT_DIR env set by the invoking hook...
  unset GIT_DIR

  # Run the publish script
  PUBLISH_SCRIPT="scripts/publish_html.sh"
  echo "invoking publish script at ${WORKING_TREE_ROOT}/${PUBLISH_SCRIPT}"
  "${PUBLISH_SCRIPT} ${DST_DIR} ${SRC_DIR}"
)
