#!/bin/bash
#

# set this to the repo root where the working tree exists
WORKING_TREE_ROOT="/the/path/to/the/stage/repo"

# read the input from git...not currently used but could
# be used to filter on branches for example.
# while read line
# do
#   echo "git ref: $line"
# done < /dev/stdin

echo "Post update hook running..."
(
  cd "${WORKING_TREE_ROOT}"
  # need to unset the GIT_DIR env set by the invoking hook
  # since the called script itself uses git cmds and from
  # within the staging repo
  unset GIT_DIR
  scripts/update_html.sh /var/www/rillbert_se/docs
)
